### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LMauc** [MiamiCenterPL/VoidUI-InfoBoxes#1]
I don't know if it's a problem with superblt or the mod, but I'll leave the crashlog

Note:
The game crashed when I created the game in the aftershock contract
[crash.txt](https://github.com/MiamiCenterPL/VoidUI-InfoBoxes/files/11952634/crash.txt)

**Comment by MiamiCenterPL** [comment]
Thank you for the report, I will get it fixed as soon as possible. Untill then please use the stable release version of the mod
