### ISSUE TITLE
[Bug] Hell's Island Timer

### ISSUE THREAD

**Issue by LMauc** [MiamiCenterPL/VoidUI-InfoBoxes#10]
I'm seriously thinking about having to go through each of the maps to see the timers hahaha

![timer infernal island](https://github.com/MiamiCenterPL/VoidUI-InfoBoxes/assets/33334792/4ba96323-8fa2-4492-8c70-07fa23da927a)

**Comment by MiamiCenterPL** [comment]
Sorry for the (huge) delay - I will get into this issue today.

I was enjoying Payday 3, and also looking into modding it.

**Comment by LMauc** [comment]
haha no problem

**Comment by MiamiCenterPL** [comment]
Do you by any chance have knowledge what this timer does?

**Comment by LMauc** [comment]
I would have to play the map again to tell you, tomorrow I will write to you to see if I can find the timer
