### ISSUE TITLE
[Bug] A couple unkown timers!

### ISSUE THREAD

**Issue by Erynnnnn** [MiamiCenterPL/VoidUI-InfoBoxes#14]
ID: e_132676
Name: open_timelock_timer
LevelID: hox_3
InstanceName: hox_estate_panic_room_001

ID: e_130129
Name: filling time
LevelID: crojob3
InstanceName: helicopter_water_003
(although now ive dsod bomb forest, im never touching that heist again xd)

**Comment by MiamiCenterPL** [comment]
Hello and thank you for your issue report. I will look into these unassigned timers today.
