### ISSUE TITLE
[Bug] Auto-update results in a broken mod folder

### ISSUE THREAD

**Issue by Vitaliuz** [MiamiCenterPL/VoidUI-InfoBoxes#15]
**Describe the bug**
Today the SuperBLT's auto-update decided to notify about an update of this mod, and I allowed it to update - resulting in broken mod folder.
The mod was disabled, ofc, as there's no mod body _(.lua, ect)_ in the folder - only a bunch of .md files _(and other stuff)_ in it.
It's strange, as I played yesterday, and there was no notification about the update, and there shouldn't be one in the first place - as the last commit is dated as of 2023.
The .zip _(in the "downloads" folder)_ was broken as well, containing the same files.

**To Reproduce**
1. Allow the ingame auto-update to update the mod.

**Expected behavior**
Expected to it actually auto-update. Or don't show a notification - as there's no new versions anyways. =)

**Screenshots**
![VoidUI InfoBoxes  1](https://github.com/MiamiCenterPL/VoidUI-InfoBoxes/assets/82944354/945425f4-3890-43dc-975f-246bd53d7ff0)
![VoidUI InfoBoxes  2](https://github.com/MiamiCenterPL/VoidUI-InfoBoxes/assets/82944354/da975379-4749-4669-9f87-5cb38e0cc5db)

**Additional context**
I noticed _(after the "update")_ that the joker icon disappeared, so I went to the mod options to check that out - only to find out that there's no options for the mod at all, and therefore I had to check the mod folder next.
Replaced the mod folder with the one from the latest commit - and got it working back again _(did a couple heists to be sure)._

I don't know whether it was a one-time thing _(which happened to me only)_ - but I thought that it won't hurt to report that. =)

**Comment by MiamiCenterPL** [comment]
This seems to be caused by an outdated BeardLib mod instance - please use the latest version of it.
My mod uses the update functions of BeardLib - I double checked the settings and on my mod's side it's all correct.
In case this happens with the latest version of BeardLib, please make an issue ticket on their [GitHub](https://github.com/simon-wh/PAYDAY-2-BeardLib)

**Comment by Vitaliuz** [comment]
My BeardLib is already at the latest version _(it auto-updates =])._
Double-checked the newest version from its github, and the files in the "old" folder are bit-exact _(hash wise)_ to the latest v4.88 of BeardLib _(they were in that state for almost a year now, but I checked just for the lulz anyway)._

All's well that ends well ... I guess.

**Comment by Vitaliuz** [comment]
Recent update broke the mod again. The very same way described above.
BeardLib has updated itself prior to the mod _(couple days, iirc),_ and ** each and every** mod out of 63 mods I use _(besides this one)_ auto-updated itself w/o a problem as well. So ... a _**wild guess**_ will be that the BeardLib isn't the problem here. =)

**Comment by Vitaliuz** [comment]
Recent update broke the mod again. The very same way described above.
BeardLib has updated itself prior to the mod _(couple days, iirc),_ and **each and every** mod out of 63 mods I use _(besides this one)_ auto-updated itself w/o a problem as well. So ... a _**wild guess**_ will be that the BeardLib isn't the problem here. =)

**Comment by MiamiCenterPL** [comment]
> Recent update broke the mod again. The very same way described above.
> BeardLib has updated itself prior to the mod _(couple days, iirc),_ and **each and every** mod out of 63 mods I use _(besides this one)_ auto-updated itself w/o a problem as well. So ... a _**wild guess**_ will be that the BeardLib isn't the problem here. =)

My mod depends on the BeardLib update functionality - It does not implement anything related to auto update on it's own. 
It is BeardLib that somehow fails to update my mod using GitHub update feature.
