### ISSUE TITLE
[Crash] ObjectInteractionManager.lua:84

### ISSUE THREAD

**Issue by Renytenz** [MiamiCenterPL/VoidUI-InfoBoxes#16]
Been getting this crash on different maps several times. Last time on Meltdown when I was throwing bags into the car. Happens periodically, not always when interacting with bags. 
[crash.txt](https://github.com/user-attachments/files/15656869/crash.txt)

```
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   


-------------------------------

Current thread: Main
Script stack:
                functionCall()  @mods/VoidUI-InfoBoxes-main/lua/ObjectInteractionManager.lua:84  
                      Update()  @mods/base/req/core/DelayedCalls.lua:24             
                        func()  @mods/base/req/core/DelayedCalls.lua:10             
                        Call()  @mods/base/req/core/Hooks.lua:85                    
                        func()  @mods/base/lua/GameSetup.lua:3                      
                      update()  @mods/base/req/core/Hooks.lua:253                   
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:559                   

-------------------------------

System information:
	Application version : 1.143.243
	CPU : 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3070 Ti / nvldumd.dll[31.0.15.5244]
	Language : english
	Memory :     32605MB 332KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Динамики (EDIFIER S350DB Stereo))


```

**Comment by Renytenz** [comment]
Got same error while grabbing gabs at overdrill. Almost at the end of the overdrill. So not map specific.

**Comment by MiamiCenterPL** [comment]
Please verify your game files - I hope it'll help

**Comment by MiamiCenterPL** [comment]
Eventually try updating to the the latest commit - it should fix this issue.
(Just click download on the main github site, and install it as you do with any other mods)
If that solves your issue please close this issue.

**Comment by Renytenz** [comment]
Veryfying the files didn't find anything wrong, going to try the new version, thank you! Will close the issue and open a new one if any crash occurs.

**Comment by Renytenz** [comment]
Veryfying the files didn't find anything wrong, going to try the new version, thank you! Will close the issue and open a new one if any crash occurs.

**Comment by DarSitam** [comment]
You might want to reopen the issue, I got the exact same crash today
[crash.txt](https://github.com/user-attachments/files/16117148/crash.txt)

**Comment by MiamiCenterPL** [comment]
> You might want to reopen the issue, I got the exact same crash today. And like the first post, it was when i threw a bag onto a forklift
> [crash.txt](https://github.com/user-attachments/files/16117148/crash.txt)
> 

Please update to the latest version. It should have this crash fixed.

**Comment by DarSitam** [comment]
> > You might want to reopen the issue, I got the exact same crash today. And like the first post, it was when i threw a bag onto a forklift
> > [crash.txt](https://github.com/user-attachments/files/16117148/crash.txt)
> 
> Please update to the latest version. It should have this crash fixed.

done, i'll report if i crashed again

**Comment by Renytenz** [comment]
Took a break from the game, started playing again today and got the same crash in second game, while carrying bags to the van :(
[crash.txt](https://github.com/user-attachments/files/16203663/crash.txt)

**Comment by MiamiCenterPL** [comment]
I've added one more check to the code, which I thought wasn't necessary - it may solve your issue. Seems like your game is modded in some weird way that it causes my mod to fail sometimes.
Please give it a try with the newest commit

**Comment by Renytenz** [comment]
Played several games, stable so far, thahks a lot!
