### ISSUE TITLE
[Bug] Unknown timers on Border Crystals

### ISSUE THREAD

**Issue by DarSitam** [MiamiCenterPL/VoidUI-InfoBoxes#17]
ID: e_151453
Name: 20sec_timer
LevelID: mex_cooking
InstanceName: dah_blackhawk_fwd_repel_001

**Comment by MiamiCenterPL** [comment]
After investigating the heist itself, I came into the conclusion that this very timer should be ignored by this mod.
With latest commit I've added it to the ignored list.
Thank you for your feedback!
