### ISSUE TITLE
[Bug] A lot of missing timers on Bomb: Forest

### ISSUE THREAD

**Issue by DarSitam** [MiamiCenterPL/VoidUI-InfoBoxes#18]
Some screenshots since there was a lot of error messages. They're probably related to the chopper filling up the train

![20240713200932_1](https://github.com/user-attachments/assets/65a7c94a-9695-4f93-a211-a3f70af310b0)
![20240713200240_1](https://github.com/user-attachments/assets/1b925b11-0cda-4928-bd99-b98704fc37f3)
![20240713200318_1](https://github.com/user-attachments/assets/41bc8fc5-a1e6-4514-b375-e5825e44370b)
![20240713200742_1](https://github.com/user-attachments/assets/5e1395fa-5ce2-469b-9434-1977751a1c48)

**Comment by MiamiCenterPL** [comment]
I have added these timers to the filters, thank you for your feedback!
