### ISSUE TITLE
issue with hud scripts

### ISSUE THREAD

**Issue by mossmuncher-o3o** [MiamiCenterPL/VoidUI-InfoBoxes#19]
**Describe the bug**
Info does not display, at all chat fills with messages from [VoidUI Infoboxes] saying that something is wrong with the HUD scripts and states what specifically failed to load (gagepacks, Drama, enemies, kills)

**To Reproduce**
1. Play any heist
2. Allow npcs to spawn

**Expected behavior**
For the info to load and display with no issue or error messages in chat

**Screenshots**
![image](https://github.com/user-attachments/assets/c0821ed1-c6ab-4d85-bc54-aa3062558f1b)

**Additional context**
I'm using VanillaHUDPlus with the recommended VoidUI settings and HoloUI with the heist HUD disabled - afaik this should cause no issue.

**Comment by MiamiCenterPL** [comment]
This is happening because you have Assault Corner as well as Objective Hud disabled in VoidUI options.
The mod should work with hud space setting (Infoboxes settings) set up properly though.

**Comment by MiamiCenterPL** [comment]
Will look into this issue.

**Comment by MiamiCenterPL** [comment]
Please send me your mods/saves folder, without it I won't be able to properly recreate the issue.

**Comment by mossmuncher-o3o** [comment]
oh changing the settings worked, thanks. I guess this addon relies on VoidUI's objectives panel and the assault being enabled? (though I've gone back to disable them just to test and the info still shows)

**Comment by MiamiCenterPL** [comment]
I relies on one of these;
Assault Panel
Objective Panel
Or custom Hud Space (a fixed, static panel on your hud)

One of them has to be enabled so that Infoboxes has somewhere to go.
