### ISSUE TITLE
Unknown timer Shacklethorne

### ISSUE THREAD

**Issue by LMauc** [MiamiCenterPL/VoidUI-InfoBoxes#2]
![Sin título](https://github.com/MiamiCenterPL/VoidUI-InfoBoxes/assets/33334792/2ef09888-9cc3-41ae-9b9a-1b4478c2146f)

**Comment by MiamiCenterPL** [comment]
Good morning and thank you for the report, I will get this timer filtered by the end of the day!
Happy heisting!
