### ISSUE TITLE
[Bug] Missing possible loot on prison nightmare

### ISSUE THREAD

**Issue by LT71** [MiamiCenterPL/VoidUI-InfoBoxes#5]
**Describe the bug**
On prison nightmare there is loot on the bridge after you exit the train and move towards the escape. There are nukes on the edges in boxes you have to open and do you think it would be possible to add the nuke boxes to the container list like crates and weapon cases?

**Comment by MiamiCenterPL** [comment]
It is definately possible to count these, but the implementation might not be as efficient and cause some more lags. I have to check if the crates have unique interaction ID - if so, then it shouldn't be that bad to implement.

**Comment by LT71** [comment]
Sounds good :)
