### ISSUE TITLE
[Feature Request] Include cash briefcases on Alaskan deal as possible loot

### ISSUE THREAD

**Issue by LT71** [MiamiCenterPL/VoidUI-InfoBoxes#8]
**Is your feature request related to a problem? Please describe.**
On Alaskan deal there are some silver briefcases with money in them. Is it possible to add those as possible loot just like the black ones i requested earlier?

I have now tested every single map in the game apart from the latest heist and I have no more loot errors to report. The counter seems to work perfectly pretty much on every map.

**Comment by MiamiCenterPL** [comment]
Yes. Will be added as Possible Loot.
